[package]
name = "dcg-cv"
version = "0.1.0"
authors = ["Brendon Walsh <brendonwalsh@niamu.com>"]
edition = "2021"

[lib]
name = "dcgcv"
crate-type = ["dylib"]

[dependencies]
edn-derive = "0.5.0"
edn-rs = "0.17.4"
opencv = { version = "0.88.9", features = ["clang-runtime"] }
