[package]
name = "dcg-cv"
version = "0.1.0"
authors = ["Brendon Walsh <brendonwalsh@niamu.com>"]
edition = "2021"

[lib]
name = "dcgcv"
crate-type = ["dylib"]

[dependencies]
edn-derive = "0.7.0"
edn-rs = "0.18.0"
opencv = { version = "0.94.2", features = ["clang-runtime"] }
